"""make school_id nullable

Revision ID: 7f8378041796
Revises: 125f7470c284
Create Date: 2025-12-14 18:40:41.331711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8378041796'
down_revision = '125f7470c284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
